global:
  scrape_interval: 15s
  scrape_timeout: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.17.0.1:8082']

  - job_name: node
    static_configs:
    - targets: ['monitoring_node_exporter:9100']

  - job_name: postgres
    static_configs:
      - targets: ['exporter:9187']